---
driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04
  - name: centos-7
  - name: fedora-27
    driver:
      provision: True
      vagrantfiles:
        - test/vagrant_provisions/fedora27_vagrant_provision.rb
  - name: freebsd-10
    driver:
      provision: True
      vagrantfiles:
        - test/vagrant_provisions/freebsd_vagrant_provision.rb
  - name: freebsd-11
    driver:
      provision: True
      vagrantfiles:
        - test/vagrant_provisions/freebsd_vagrant_provision.rb

provisioner:
  name: ansible_push
  ansible_config: test/ansible.cfg
  chef_bootstrap_url: nil

transport:
  max_ssh_sessions: 6

suites:
  - name: t-guard
    provisioner:
      playbook: "test/integration/default/guard-node.yml"
  - name: t-exit
    provisioner:
      playbook: "test/integration/default/exit-node.yml"
  - name: t-guard-2publicIPs
    provisioner:
      playbook: "test/integration/default/guard-node-2-public-ips.yml"
