---
driver:
  name: vagrant
  customize:
    memory: 512

platforms:
  - name: debian-stable
    driver:
      box: bento/debian-13
  - name: debian-oldstable
    driver:
      box: bento/debian-12
  - name: ubuntu-lts
    driver:
      box: bento/ubuntu-24.04
  - name: freebsd
    driver:
      box: bento/freebsd-14
      provision: True
      vagrantfiles:
        - test/vagrant_provisions/freebsd_vagrant_provision.rb

provisioner:
  name: ansible_push
  chef_bootstrap_url: nil
  idempotency_test: true
  fail_non_idempotent: true
  diff: true

transport:
  max_ssh_sessions: 6

suites:
  - name: t-guard
    provisioner:
      playbook: "test/integration/default/guard-node.yml"
  - name: t-guard4
    provisioner:
      playbook: "test/integration/default/guard-node4.yml"
  - name: t-exit
    provisioner:
      playbook: "test/integration/default/exit-node.yml"
  - name: t-exit4
    provisioner:
      playbook: "test/integration/default/exit-node4.yml"
  - name: t-guard-nightly
    provisioner:
      playbook: "test/integration/default/guard-nightly-node.yml"
    excludes:
      - freebsd
  - name: t-guard-nightly-happy-families
    provisioner:
      playbook: "test/integration/default/guard-nightly-happy-families.yml"
    excludes:
      - freebsd
  - name: t-guard-metricsport-blackbox-exporter
    provisioner:
      playbook: "test/integration/default/guard-metricsport-blackbox.yml"
  - name: t-guard-metricsport-blackbox-alertrules
    provisioner:
      playbook: "test/integration/default/guard-metricsport-blackbox-alertrules.yml"
  - name: t-guard-metricsport-blackbox-customalertrules
    provisioner:
      playbook: "test/integration/default/guard-metricsport-blackbox-customalertrules.yml"
  - name: t-guard-nightly-metricsport-blackbox-exporter
    provisioner:
      playbook: "test/integration/default/guard-nightly-metricsport-blackbox.yml"
    excludes:
      - freebsd
  - name: t-guard-blackbox-exporter
    provisioner:
      playbook: "test/integration/default/guard-blackbox-exporter.yml"
# test for the tor_ExitRelaySetting_file feature to run
# exit and non-exit tor instances on a single machine
  - name: t-mixed
    provisioner:
      playbook: "test/integration/default/mixed-node.yml"
  - name: t-exit-per-instance-exitpolicy
    provisioner:
      playbook: "test/integration/default/exit-per-instance-exitpolicy.yml"
  - name: t-guard-2publicIPs-metricsport
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
    provisioner:
      playbook: "test/integration/default/2publicIPs-guard-metricsport.yml"
  - name: t-guard4-2publicIPs-metricsport
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
    provisioner:
      playbook: "test/integration/default/2publicIPs-guard4-metricsport.yml"
  - name: t-guard-2publicIPs
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
    provisioner:
      playbook: "test/integration/default/2publicIPs-guard-node.yml"
  - name: t-exit-2publicIPs
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
    provisioner:
      playbook: "test/integration/default/2publicIPs-exit-node.yml"
