---
# tor_intances defines the number and configurations of instances
# an instance is defined with the following fields:
# inst_name:configfile:username:groupname:pidfile:data_dir
# username/groupname is set to root to be able to bind to <1024 ports
# but privileges are dropped afterwards (torrc User parameter)
- name: Ensure Tor multi-instance configuration is present (FreeBSD)
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    line: tor_instances="${tor_instances} {{ item.ipv4 }}_{{ item.orport }}:{{ tor_ConfDir }}/{{ item.ipv4 }}_{{ item.orport }}.torrc:root:root:{{ tor_PidDir
      }}/{{ item.ipv4 }}_{{ item.orport }}/pid:{{ tor_DataDir }}/{{ item.ipv4 }}_{{ item.orport }}"
    create: true
    mode: "0644"
  loop: "{{ tor_instances }}"

# this task is a workaround, because 'service tor status'
# fails if this line is not present (which in turn fails the ansible service module)
- name: Ensure tor is enabled in /etc/rc.conf (FreeBSD)
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    line: tor_enable="YES"
    create: true
    mode: "0644"

# this affects all instances
- name: Ensure Tor instances are running and enabled (FreeBSD)
  become: true
  ansible.builtin.service:
    name: tor
    enabled: true
    state: started
