---
# OpenBSD section (uses service module)
# This is basically a copy from the Linux
# section, but it requires different service
# names and additional arguments.
# =====================================

# OpenBSD does not support multi-instance rc.d
# # so we link as many pseudo rc scripts as we need.
# # OpenBSD does not like dots in rc filenames so
# # we replace them with underscores.
- name: Create links to the service files (OpenBSD)
  become: true
  ansible.builtin.file:
    src: /etc/rc.d/tor
    state: link
    path: /etc/rc.d/tor{{ item.0.ipv4| replace('.','_') }}_{{ item.1.orport }}
  with_nested:
    - "{{ tor_ips }}"
    - "{{ tor_ports }}"

- name: Ensure Tor instances are enabled and started (OpenBSD)
  become: true
  ansible.builtin.service:
    name: tor{{ item.0.ipv4|replace('.','_') }}_{{ item.1.orport }}
    arguments: -f {{ tor_ConfDir }}/{{ item.0.ipv4 }}_{{ item.1.orport }}.torrc
    enabled: true
    state: started
  with_nested:
    - "{{ tor_ips }}"
    - "{{ tor_ports }}"
