---

- hosts: relays
  vars:
    #tor_ContactInfo: relayor-example@example.com
    tor_ExitRelay: true
    tor_ports:
        - { orport: 1, dirport: 0}
        - { orport: 2, dirport: 0}
        - { orport: 3, dirport: 0}
        - { orport: 4, dirport: 0}
  roles:
   - nusenu.relayor
